name: Stock Prediction Model

on:
  schedule:
    # 매일 한국시간 오후 9시 (UTC 12:00)에 실행
    - cron: "0 12 * * *"

  # 수동 실행 가능
  workflow_dispatch:

  # Push 시에도 실행 (테스트용)
  push:
    branches: [main]

jobs:
  stock-prediction:
    runs-on: ubuntu-latest
    timeout-minutes: 60 # 최대 1시간

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libhdf5-dev pkg-config

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run stock prediction
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          TF_CPP_MIN_LOG_LEVEL: 2 # TensorFlow 로그 레벨 설정
        run: |
          python src/stock_prediction.py

      - name: Upload prediction results
        uses: actions/upload-artifact@v4
        if: always() # 실패해도 결과 업로드
        with:
          name: prediction-results-${{ github.run_number }}
          path: outputs/
          retention-days: 30

      - name: Send notification on success
        if: success()
        run: |
          echo "주식 예측 모델이 성공적으로 실행되었습니다!"
          # Slack 알림을 원한다면 여기에 추가

      - name: Send notification on failure
        if: failure()
        run: |
          echo "주식 예측 모델 실행에 실패했습니다."
          # 실패 알림을 원한다면 여기에 추가

      - name: Send Slack notification
        if: always() && secrets.SLACK_WEBHOOK_URL != ''
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          channel: "#stock-alerts"
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./outputs
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          commit_message: "Deploy stock predictions ${{ github.run_number }}"
